-- Migration ini pada awalnya mencoba CREATE TABLE assessments
-- dengan skema berbeda dari ADR-008 (20260809000000).
-- CREATE TABLE IF NOT EXISTS di-skip karena tabel sudah ada.
-- Satu-satunya efek aktual yang berhasil: tidak ada
-- (semua policy sudah ada dari migration ADR-008).
--
-- File ini di-repair sebagai applied pada 2026-08-25
-- karena schema_migrations tidak mencatatnya meski
-- migration sudah efektif ter-apply via ADR-008.
--
-- Jangan jalankan file ini secara manual.
-- Status: REPAIR — bukan migration aktif.
